export const LISTA_PRODUCTOS_REQUEST = 'LISTA_PRODUCTOS_REQUEST'
export const LISTA_PRODUCTOS_SUCCESS = 'LISTA_PRODUCTOS_SUCCESS'
export const LISTA_PRODUCTOS_FAIL = 'LISTA_PRODUCTOS_FAIL'

export const DETALLES_PRODUCTO_REQUEST = 'DETALLES_PRODUCTO_REQUEST'
export const DETALLES_PRODUCTO_SUCCESS = 'DETALLES_PRODUCTO_SUCCESS'
export const DETALLES_PRODUCTO_FAIL = 'DETALLES_PRODUCTO_FAIL'